kare_csv_file:
  cron: "45 12 * * *"
  class: KareCsvFileScheduler
  queue: default
  description: "This job schedules kare csv file every day at 12:45"
kare_pars:
  cron: "00 12 * * *"
  class: KareParsScheduler
  queue: default
  description: "This job schedules kare pars every day at 12:00"
idc_csv_file:
  cron: "30 11 * * *"
  class: IdcCsvFileScheduler
  queue: default
  description: "This job schedules idc csv file every day at 11:30"
idc_pars:
  cron: "00 11 * * *"
  class: IdcParsScheduler
  queue: default
  description: "This job schedules idc pars every day at 11:00"
log_files:
  cron: "50 23 * * *"
  class: LogFilesScheduler
  queue: default
  description: "This job logs files every day at 23:50"