kare_csv_file:
  cron: "45 18 * * *"
  class: KareCsvFileScheduler
  queue: default
  description: "This job schedules kare csv file every day at 18:45"
kare_pars:
  cron: "00 18 * * *"
  class: KareParsScheduler
  queue: default
  description: "This job schedules kare pars every day at 18:00"
idc_csv_file:
  cron: "30 17 * * *"
  class: IdcCsvFileScheduler
  queue: default
  description: "This job schedules idc csv file every day at 17:30"
idc_pars:
  cron: "00 17 * * *"
  class: IdcParsScheduler
  queue: default
  description: "This job schedules idc pars every day at 17:00"
log_files:
  cron: "50 23 * * *"
  class: LogFilesScheduler
  queue: default
  description: "This job logs files every day at 23:50"