:concurrency: 5

:queues:
    - default
    - kare_pars_page
    - kare_collect_links
    - idc_import
    - idc_pars_url
    - idc_csv_param
:scheduler:
  :dynamic: true


development:
  :concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20